export const MODAL_OPEN = "MODAL_OPEN";

export const MAHASISWA_SELECTED = "MAHASISWA_SELECTED";

export const MAHASISWA_FETCH_REQUESTED = "MAHASISWA_FETCH_REQUESTED";
export const MAHASISWA_FETCH_SUCCEEDED = "MAHASISWA_FETCH_SUCCEEDED";
export const MAHASISWA_FETCH_FAILED = "MAHASISWA_FETCH_FAILED";

export const MAHASISWA_ADD_REQUESTED = "MAHASISWA_ADD_REQUESTED";
export const MAHASISWA_ADD_SUCCEEDED = "MAHASISWA_ADD_SUCCEEDED";
export const MAHASISWA_ADD_FAILED = "MAHASISWA_ADD_FAILED";

export const MAHASISWA_UPDATE_REQUESTED = "MAHASISWA_UPDATE_REQUESTED";
export const MAHASISWA_UPDATE_SUCCEEDED = "MAHASISWA_UPDATE_SUCCEEDED";
export const MAHASISWA_UPDATE_FAILED = "MAHASISWA_UPDATE_FAILED";

export const MAHASISWA_DELETE_REQUESTED = "MAHASISWA_DELETE_REQUESTED";
export const MAHASISWA_DELETE_SUCCEEDED = "MAHASISWA_DELETE_SUCCEEDED";
export const MAHASISWA_DELETE_FAILED = "MAHASISWA_DELETE_FAILED";
